### PR TITLE
feat: add main function to short#5

### PR DESCRIPTION
**Pull request by Crimson-Blade**
Added main function

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Lol, the main function was not asked. Only the definition. I can still merge this if you want but I think you should add a comment telling that this part is not required.

**Comment by HarshKhandeparkar** [comment]
:partying_face: First PR

**Comment by HarshKhandeparkar** [comment]
@Crimson-Blade

**Comment by Crimson-Blade** [comment]
ok made that comment

**Comment by HarshKhandeparkar** [comment]
Noicee!

**Pull request merged**
